### ISSUE TITLE
"ReferenceError: Can't find variable: specljs"

### ISSUE THREAD

**Issue by zilti** [slagyr/speclj#55]
I get this error when trying to use specljs with cljsbuild 2.7.4:

```
SyntaxError: Parse error

ReferenceError: Can't find variable: specljs

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():6
  phantomjs://webpage.evaluate():6
```

This is the test runner:

``` javascript
var fs = require("fs");
var p = require('webpage').create();
var sys = require('system');

p.onConsoleMessage = function (x) {
    fs.write("/dev/stdout", x, "w");
};

p.injectJs(phantom.args[0]);

var result = p.evaluate(function () {
  specljs.run.standard.armed = true;
  return specljs.run.standard.run_specs(
     cljs.core.keyword("color"), true
  );
});

phantom.exit(result);
```

And this is the actual test cljs file:

``` clojure
(ns input-frontend.core-test
  (:require specljs.core
            [input-frontend.core :refer []])
  (:require-macros [specljs.core :refer [describe it should]]))

(describe "Does it work?"
          (it "tests if testing tests."
              (should true)))
```

I'm using an html-file to load the javascript dependencies and finally the compiled clojurescript file.

**Comment by Luke1298** [comment]
I know this has been closed a long time -- but the error for me was caused because some files in my test/cljs weren't compling properly. The "Can't find variable: specljs" was a red harring. Also doing `lein new specljs foo` wasn't working -- not sure why exactly, but I had to configure everything differently than they did. Make sure that you aren't trying to actually render any of your components if you are using reagent.
